displayName=GroupScape Tracker
author=Christopher Brown
support=
description=Tracks information (skills, inventory, bank, etc.) about your RuneScape group's players and sends it to a website for other group members to view
tags=group,tracker,party
plugins=com.groupscape.GroupScapeTrackerPlugin
build=standard