displayName=GroupScape
author=MayzrDev
support=https://github.com/MayzrDev/groupscape-plugin/issues
description=Party up with friends! With GroupScape, you can now group up with your friends and track their stats and location in real-time.
tags=group,tracker,party
plugins=com.groupscape.GroupScapeTrackerPlugin
build=standard
